version: 0.2
# Build the UCLDC Nuxeo Docker image and upload it to ECR.
phases:
  pre_build:
    on-failure: ABORT
    commands:
      # log into ECR private
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 866216109762.dkr.ecr.us-west-2.amazonaws.com
      # log into Nuxeo's private docker repo
      - docker login docker-private.packages.nuxeo.com -u ${NuxeoPrivateDockerLogin} -p ${NuxeoPrivateDockerPassword}
  build:
    on-failure: ABORT
    commands:
      - REPOSITORY_URI=${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepo}
      - docker build -t $REPOSITORY_URI --build-arg NUXEO_VERSION=${NuxeoVersion} --build-arg NUXEO_CUSTOM_PACKAGE=${NuxeoCustomPackage} --build-arg CLID .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$GIT_TAG
  post_build:
    commands:
      # push docker image to ECR
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$GIT_TAG